INSERT INTO Environment.Country(CountryID,Name) VALUES (1,'Afghanistan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (2,'Albania');
INSERT INTO Environment.Country(CountryID,Name) VALUES (3,'Algeria');
INSERT INTO Environment.Country(CountryID,Name) VALUES (4,'American Samoa');
INSERT INTO Environment.Country(CountryID,Name) VALUES (5,'Andorra');
INSERT INTO Environment.Country(CountryID,Name) VALUES (6,'Angola');
INSERT INTO Environment.Country(CountryID,Name) VALUES (7,'Antigua and Barbuda');
INSERT INTO Environment.Country(CountryID,Name) VALUES (8,'Argentina');
INSERT INTO Environment.Country(CountryID,Name) VALUES (9,'Armenia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (10,'Aruba');
INSERT INTO Environment.Country(CountryID,Name) VALUES (11,'Australia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (12,'Austria');
INSERT INTO Environment.Country(CountryID,Name) VALUES (13,'Azerbaijan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (14,'Bahamas, The');
INSERT INTO Environment.Country(CountryID,Name) VALUES (15,'Bahrain');
INSERT INTO Environment.Country(CountryID,Name) VALUES (16,'Bangladesh');
INSERT INTO Environment.Country(CountryID,Name) VALUES (17,'Barbados');
INSERT INTO Environment.Country(CountryID,Name) VALUES (18,'Belarus');
INSERT INTO Environment.Country(CountryID,Name) VALUES (19,'Belgium');
INSERT INTO Environment.Country(CountryID,Name) VALUES (20,'Belize');
INSERT INTO Environment.Country(CountryID,Name) VALUES (21,'Benin');
INSERT INTO Environment.Country(CountryID,Name) VALUES (22,'Bermuda');
INSERT INTO Environment.Country(CountryID,Name) VALUES (23,'Bhutan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (24,'Bolivia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (25,'Bosnia and Herzegovina');
INSERT INTO Environment.Country(CountryID,Name) VALUES (26,'Botswana');
INSERT INTO Environment.Country(CountryID,Name) VALUES (27,'Brazil');
INSERT INTO Environment.Country(CountryID,Name) VALUES (28,'Brunei Darussalam');
INSERT INTO Environment.Country(CountryID,Name) VALUES (29,'Bulgaria');
INSERT INTO Environment.Country(CountryID,Name) VALUES (30,'Burkina Faso');
INSERT INTO Environment.Country(CountryID,Name) VALUES (31,'Burundi');
INSERT INTO Environment.Country(CountryID,Name) VALUES (32,'Cabo Verde');
INSERT INTO Environment.Country(CountryID,Name) VALUES (33,'Cambodia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (34,'Cameroon');
INSERT INTO Environment.Country(CountryID,Name) VALUES (35,'Canada');
INSERT INTO Environment.Country(CountryID,Name) VALUES (36,'Cayman Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (37,'Central African Republic');
INSERT INTO Environment.Country(CountryID,Name) VALUES (38,'Chad');
INSERT INTO Environment.Country(CountryID,Name) VALUES (39,'Channel Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (40,'Chile');
INSERT INTO Environment.Country(CountryID,Name) VALUES (41,'China');
INSERT INTO Environment.Country(CountryID,Name) VALUES (42,'Hong Kong SAR, China');
INSERT INTO Environment.Country(CountryID,Name) VALUES (43,'Macao SAR, China');
INSERT INTO Environment.Country(CountryID,Name) VALUES (44,'Colombia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (45,'Comoros');
INSERT INTO Environment.Country(CountryID,Name) VALUES (46,'Congo, Dem. Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (47,'Congo, Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (48,'Costa Rica');
INSERT INTO Environment.Country(CountryID,Name) VALUES (49,'Cote d''Ivoire');
INSERT INTO Environment.Country(CountryID,Name) VALUES (50,'Croatia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (51,'Cuba');
INSERT INTO Environment.Country(CountryID,Name) VALUES (52,'Curacao');
INSERT INTO Environment.Country(CountryID,Name) VALUES (53,'Cyprus');
INSERT INTO Environment.Country(CountryID,Name) VALUES (54,'Czech Republic');
INSERT INTO Environment.Country(CountryID,Name) VALUES (55,'Denmark');
INSERT INTO Environment.Country(CountryID,Name) VALUES (56,'Djibouti');
INSERT INTO Environment.Country(CountryID,Name) VALUES (57,'Dominica');
INSERT INTO Environment.Country(CountryID,Name) VALUES (58,'Dominican Republic');
INSERT INTO Environment.Country(CountryID,Name) VALUES (59,'Ecuador');
INSERT INTO Environment.Country(CountryID,Name) VALUES (60,'Egypt, Arab Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (61,'El Salvador');
INSERT INTO Environment.Country(CountryID,Name) VALUES (62,'Equatorial Guinea');
INSERT INTO Environment.Country(CountryID,Name) VALUES (63,'Eritrea');
INSERT INTO Environment.Country(CountryID,Name) VALUES (64,'Estonia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (65,'Ethiopia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (66,'Faroe Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (67,'Fiji');
INSERT INTO Environment.Country(CountryID,Name) VALUES (68,'Finland');
INSERT INTO Environment.Country(CountryID,Name) VALUES (69,'France');
INSERT INTO Environment.Country(CountryID,Name) VALUES (70,'French Polynesia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (71,'Gabon');
INSERT INTO Environment.Country(CountryID,Name) VALUES (72,'Gambia, The');
INSERT INTO Environment.Country(CountryID,Name) VALUES (73,'Georgia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (74,'Germany');
INSERT INTO Environment.Country(CountryID,Name) VALUES (75,'Ghana');
INSERT INTO Environment.Country(CountryID,Name) VALUES (76,'Greece');
INSERT INTO Environment.Country(CountryID,Name) VALUES (77,'Greenland');
INSERT INTO Environment.Country(CountryID,Name) VALUES (78,'Grenada');
INSERT INTO Environment.Country(CountryID,Name) VALUES (79,'Guam');
INSERT INTO Environment.Country(CountryID,Name) VALUES (80,'Guatemala');
INSERT INTO Environment.Country(CountryID,Name) VALUES (81,'Guinea');
INSERT INTO Environment.Country(CountryID,Name) VALUES (82,'Guinea-Bissau');
INSERT INTO Environment.Country(CountryID,Name) VALUES (83,'Guyana');
INSERT INTO Environment.Country(CountryID,Name) VALUES (84,'Haiti');
INSERT INTO Environment.Country(CountryID,Name) VALUES (85,'Honduras');
INSERT INTO Environment.Country(CountryID,Name) VALUES (86,'Hungary');
INSERT INTO Environment.Country(CountryID,Name) VALUES (87,'Iceland');
INSERT INTO Environment.Country(CountryID,Name) VALUES (88,'India');
INSERT INTO Environment.Country(CountryID,Name) VALUES (89,'Indonesia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (90,'Iran, Islamic Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (91,'Iraq');
INSERT INTO Environment.Country(CountryID,Name) VALUES (92,'Ireland');
INSERT INTO Environment.Country(CountryID,Name) VALUES (93,'Isle of Man');
INSERT INTO Environment.Country(CountryID,Name) VALUES (94,'Israel');
INSERT INTO Environment.Country(CountryID,Name) VALUES (95,'Italy');
INSERT INTO Environment.Country(CountryID,Name) VALUES (96,'Jamaica');
INSERT INTO Environment.Country(CountryID,Name) VALUES (97,'Japan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (98,'Jordan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (99,'Kazakhstan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (100,'Kenya');
INSERT INTO Environment.Country(CountryID,Name) VALUES (101,'Kiribati');
INSERT INTO Environment.Country(CountryID,Name) VALUES (102,'Korea, Dem. People’s Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (103,'Korea, Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (104,'Kosovo');
INSERT INTO Environment.Country(CountryID,Name) VALUES (105,'Kuwait');
INSERT INTO Environment.Country(CountryID,Name) VALUES (106,'Kyrgyz Republic');
INSERT INTO Environment.Country(CountryID,Name) VALUES (107,'Lao PDR');
INSERT INTO Environment.Country(CountryID,Name) VALUES (108,'Latvia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (109,'Lebanon');
INSERT INTO Environment.Country(CountryID,Name) VALUES (110,'Lesotho');
INSERT INTO Environment.Country(CountryID,Name) VALUES (111,'Liberia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (112,'Libya');
INSERT INTO Environment.Country(CountryID,Name) VALUES (113,'Liechtenstein');
INSERT INTO Environment.Country(CountryID,Name) VALUES (114,'Lithuania');
INSERT INTO Environment.Country(CountryID,Name) VALUES (115,'Luxembourg');
INSERT INTO Environment.Country(CountryID,Name) VALUES (116,'North Macedonia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (117,'Madagascar');
INSERT INTO Environment.Country(CountryID,Name) VALUES (118,'Malawi');
INSERT INTO Environment.Country(CountryID,Name) VALUES (119,'Malaysia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (120,'Maldives');
INSERT INTO Environment.Country(CountryID,Name) VALUES (121,'Mali');
INSERT INTO Environment.Country(CountryID,Name) VALUES (122,'Malta');
INSERT INTO Environment.Country(CountryID,Name) VALUES (123,'Marshall Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (124,'Mauritania');
INSERT INTO Environment.Country(CountryID,Name) VALUES (125,'Mauritius');
INSERT INTO Environment.Country(CountryID,Name) VALUES (126,'Mexico');
INSERT INTO Environment.Country(CountryID,Name) VALUES (127,'Micronesia, Fed. Sts.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (128,'Moldova');
INSERT INTO Environment.Country(CountryID,Name) VALUES (129,'Monaco');
INSERT INTO Environment.Country(CountryID,Name) VALUES (130,'Mongolia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (131,'Montenegro');
INSERT INTO Environment.Country(CountryID,Name) VALUES (132,'Morocco');
INSERT INTO Environment.Country(CountryID,Name) VALUES (133,'Mozambique');
INSERT INTO Environment.Country(CountryID,Name) VALUES (134,'Myanmar');
INSERT INTO Environment.Country(CountryID,Name) VALUES (135,'Namibia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (136,'Nepal');
INSERT INTO Environment.Country(CountryID,Name) VALUES (137,'Netherlands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (138,'New Caledonia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (139,'New Zealand');
INSERT INTO Environment.Country(CountryID,Name) VALUES (140,'Nicaragua');
INSERT INTO Environment.Country(CountryID,Name) VALUES (141,'Niger');
INSERT INTO Environment.Country(CountryID,Name) VALUES (142,'Nigeria');
INSERT INTO Environment.Country(CountryID,Name) VALUES (143,'Northern Mariana Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (144,'Norway');
INSERT INTO Environment.Country(CountryID,Name) VALUES (145,'Oman');
INSERT INTO Environment.Country(CountryID,Name) VALUES (146,'Pakistan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (147,'Palau');
INSERT INTO Environment.Country(CountryID,Name) VALUES (148,'Panama');
INSERT INTO Environment.Country(CountryID,Name) VALUES (149,'Papua New Guinea');
INSERT INTO Environment.Country(CountryID,Name) VALUES (150,'Paraguay');
INSERT INTO Environment.Country(CountryID,Name) VALUES (151,'Peru');
INSERT INTO Environment.Country(CountryID,Name) VALUES (152,'Philippines');
INSERT INTO Environment.Country(CountryID,Name) VALUES (153,'Poland');
INSERT INTO Environment.Country(CountryID,Name) VALUES (154,'Portugal');
INSERT INTO Environment.Country(CountryID,Name) VALUES (155,'Puerto Rico');
INSERT INTO Environment.Country(CountryID,Name) VALUES (156,'Qatar');
INSERT INTO Environment.Country(CountryID,Name) VALUES (157,'Romania');
INSERT INTO Environment.Country(CountryID,Name) VALUES (158,'Russian Federation');
INSERT INTO Environment.Country(CountryID,Name) VALUES (159,'Rwanda');
INSERT INTO Environment.Country(CountryID,Name) VALUES (160,'Samoa');
INSERT INTO Environment.Country(CountryID,Name) VALUES (161,'San Marino');
INSERT INTO Environment.Country(CountryID,Name) VALUES (162,'Sao Tome and Principe');
INSERT INTO Environment.Country(CountryID,Name) VALUES (163,'Saudi Arabia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (164,'Senegal');
INSERT INTO Environment.Country(CountryID,Name) VALUES (165,'Serbia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (166,'Seychelles');
INSERT INTO Environment.Country(CountryID,Name) VALUES (167,'Sierra Leone');
INSERT INTO Environment.Country(CountryID,Name) VALUES (168,'Singapore');
INSERT INTO Environment.Country(CountryID,Name) VALUES (169,'Sint Maarten (Dutch part)');
INSERT INTO Environment.Country(CountryID,Name) VALUES (170,'Slovak Republic');
INSERT INTO Environment.Country(CountryID,Name) VALUES (171,'Slovenia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (172,'Solomon Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (173,'Somalia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (174,'South Africa');
INSERT INTO Environment.Country(CountryID,Name) VALUES (175,'South Sudan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (176,'Spain');
INSERT INTO Environment.Country(CountryID,Name) VALUES (177,'Sri Lanka');
INSERT INTO Environment.Country(CountryID,Name) VALUES (178,'St. Kitts and Nevis');
INSERT INTO Environment.Country(CountryID,Name) VALUES (179,'St. Lucia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (180,'St. Martin (French part)');
INSERT INTO Environment.Country(CountryID,Name) VALUES (181,'St. Vincent and the Grenadines');
INSERT INTO Environment.Country(CountryID,Name) VALUES (182,'Sudan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (183,'Suriname');
INSERT INTO Environment.Country(CountryID,Name) VALUES (184,'Eswatini');
INSERT INTO Environment.Country(CountryID,Name) VALUES (185,'Sweden');
INSERT INTO Environment.Country(CountryID,Name) VALUES (186,'Switzerland');
INSERT INTO Environment.Country(CountryID,Name) VALUES (187,'Syrian Arab Republic');
INSERT INTO Environment.Country(CountryID,Name) VALUES (188,'Tajikistan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (189,'Tanzania');
INSERT INTO Environment.Country(CountryID,Name) VALUES (190,'Thailand');
INSERT INTO Environment.Country(CountryID,Name) VALUES (191,'Timor-Leste');
INSERT INTO Environment.Country(CountryID,Name) VALUES (192,'Togo');
INSERT INTO Environment.Country(CountryID,Name) VALUES (193,'Tonga');
INSERT INTO Environment.Country(CountryID,Name) VALUES (194,'Trinidad and Tobago');
INSERT INTO Environment.Country(CountryID,Name) VALUES (195,'Tunisia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (196,'Turkey');
INSERT INTO Environment.Country(CountryID,Name) VALUES (197,'Turkmenistan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (198,'Turks and Caicos Islands');
INSERT INTO Environment.Country(CountryID,Name) VALUES (199,'Tuvalu');
INSERT INTO Environment.Country(CountryID,Name) VALUES (200,'Uganda');
INSERT INTO Environment.Country(CountryID,Name) VALUES (201,'Ukraine');
INSERT INTO Environment.Country(CountryID,Name) VALUES (202,'United Arab Emirates');
INSERT INTO Environment.Country(CountryID,Name) VALUES (203,'United Kingdom');
INSERT INTO Environment.Country(CountryID,Name) VALUES (204,'United States');
INSERT INTO Environment.Country(CountryID,Name) VALUES (205,'Uruguay');
INSERT INTO Environment.Country(CountryID,Name) VALUES (206,'Uzbekistan');
INSERT INTO Environment.Country(CountryID,Name) VALUES (207,'Vanuatu');
INSERT INTO Environment.Country(CountryID,Name) VALUES (208,'Venezuela, RB');
INSERT INTO Environment.Country(CountryID,Name) VALUES (209,'Vietnam');
INSERT INTO Environment.Country(CountryID,Name) VALUES (210,'Virgin Islands (U.S.)');
INSERT INTO Environment.Country(CountryID,Name) VALUES (211,'West Bank and Gaza');
INSERT INTO Environment.Country(CountryID,Name) VALUES (212,'Yemen, Rep.');
INSERT INTO Environment.Country(CountryID,Name) VALUES (213,'Zambia');
INSERT INTO Environment.Country(CountryID,Name) VALUES (214,'Zimbabwe');
