INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',1,1,'Afghanistan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',2,2,'Albania');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',3,3,'Algeria');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',24.0,58.8,13.0,4,4,'American Samoa');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (462.0,0.0,'','',5,5,'Andorra');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',6,6,'Angola');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (532.0,26.0,552.7,43.0,7,7,'Antigua and Barbuda');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',8,8,'Argentina');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',9,9,'Armenia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (873.0,6.0,'',23.0,10,10,'Aruba');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',11,11,'Australia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',12,12,'Austria');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',13,13,'Azerbaijan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',131.0,'',227.0,14,14,'Bahamas, The');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',131.0,'','',15,15,'Bahrain');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',16,16,'Bangladesh');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',59.0,'',109.0,17,17,'Barbados');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',18,18,'Belarus');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',19,19,'Belgium');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (495.0,200.0,'',228.0,20,20,'Belize');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',21,21,'Benin');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (576.0,21.0,632.9,31.0,22,22,'Bermuda');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',555.0,'','',23,23,'Bhutan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',24,24,'Bolivia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',25,25,'Bosnia and Herzegovina');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',26,26,'Botswana');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',27,27,'Brazil');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',342.0,'','',28,28,'Brunei Darussalam');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',29,29,'Bulgaria');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',30,30,'Burkina Faso');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (440.0,789.0,'','',31,31,'Burundi');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (491.0,81.0,'',151.0,32,32,'Cabo Verde');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',33,33,'Cambodia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',34,34,'Cameroon');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',35,35,'Canada');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (543.0,14.0,'',29.0,36,36,'Cayman Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (301.0,'','','',37,37,'Central African Republic');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (730.0,'','','',38,38,'Chad');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',39,39,'Channel Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',40,40,'Chile');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',41,41,'China');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',476.0,'','',42,42,'Hong Kong SAR, China');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',12.0,'',151.0,43,43,'Macao SAR, China');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',44,44,'Colombia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (154.0,59.0,564.2,284.0,45,45,'Comoros');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',46,46,'Congo, Dem. Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',47,47,'Congo, Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',48,48,'Costa Rica');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',49,49,'Cote d''Ivoire');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',50,50,'Croatia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',51,51,'Cuba');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',52,52,'Curacao');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',315.0,'',642.0,53,53,'Cyprus');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',54,54,'Czech Republic');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',55,55,'Denmark');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (722.0,257.0,'',634.0,56,56,'Djibouti');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (136.0,21.0,222.8,41.0,57,57,'Dominica');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',58,58,'Dominican Republic');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',59,59,'Ecuador');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',60,60,'Egypt, Arab Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',61,61,'El Salvador');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',37.0,'','',62,62,'Equatorial Guinea');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (697.0,'','','',63,63,'Eritrea');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',951.0,'','',64,64,'Estonia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',65,65,'Ethiopia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',7.0,'',39.0,66,66,'Faroe Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (598.0,344.0,'',715.0,67,67,'Fiji');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',68,68,'Finland');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',69,69,'France');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',37.0,'',99.0,70,70,'French Polynesia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (803.0,838.0,'','',71,71,'Gabon');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',500.0,'','',72,72,'Gambia, The');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (513.0,'','','',73,73,'Georgia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',74,74,'Germany');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',75,75,'Ghana');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',76,76,'Greece');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',231.0,'',29.0,77,77,'Greenland');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (506.0,26.0,726.2,37.0,78,78,'Grenada');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (242.0,2.0,85.9,71.0,79,79,'Guam');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',80,80,'Guatemala');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',81,81,'Guinea');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',990.0,'','',82,82,'Guinea-Bissau');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (271.0,'','','',83,83,'Guyana');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',84,84,'Haiti');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',85,85,'Honduras');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',86,86,'Hungary');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',369.0,'',359.0,87,87,'Iceland');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',88,88,'India');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',89,89,'Indonesia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',90,90,'Iran, Islamic Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',91,91,'Iraq');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',92,92,'Ireland');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',93,93,'Isle of Man');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',94,94,'Israel');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',95,95,'Italy');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',656.0,'','',96,96,'Jamaica');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',97,97,'Japan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',605.0,'','',98,98,'Jordan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',99,99,'Kazakhstan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',100,100,'Kenya');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',4.0,'',16.0,101,101,'Kiribati');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (62.0,'','','',102,102,'Korea, Dem. People’s Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',103,103,'Korea, Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',0.0,'',0.0,104,104,'Kosovo');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',704.0,'','',105,105,'Kuwait');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',106,106,'Kyrgyz Republic');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',107,107,'Lao PDR');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',108,108,'Latvia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',462.0,'','',109,109,'Lebanon');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',428.0,'','',110,110,'Lesotho');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',337.0,'','',111,111,'Liberia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (935.0,'','','',112,112,'Libya');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',113,113,'Liechtenstein');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (44.0,'','','',114,114,'Lithuania');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',473.0,'','',115,115,'Luxembourg');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',526.0,'','',116,116,'North Macedonia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',117,117,'Madagascar');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',118,118,'Malawi');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',119,119,'Malaysia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',27.0,'',52.0,120,120,'Maldives');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',121,121,'Mali');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',61.0,'',141.0,122,122,'Malta');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',0.0,'',8.0,123,123,'Marshall Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (103.0,'','','',124,124,'Mauritania');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',170.0,'',311.0,125,125,'Mauritius');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',126,126,'Mexico');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',11.0,'',30.0,127,127,'Micronesia, Fed. Sts.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (150.0,686.0,'','',128,128,'Moldova');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',129,129,'Monaco');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',130,130,'Mongolia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',0.0,'',0.0,131,131,'Montenegro');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',132,132,'Morocco');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',133,133,'Mozambique');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',134,134,'Myanmar');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',135,135,'Namibia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',136,136,'Nepal');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',137,137,'Netherlands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',98.0,'',215.0,138,138,'New Caledonia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',139,139,'New Zealand');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',140,140,'Nicaragua');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',141,141,'Niger');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',142,142,'Nigeria');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',0.0,12.5,12.0,143,143,'Northern Mariana Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',144,144,'Norway');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',145,145,'Oman');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',146,146,'Pakistan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',0.0,'',1.0,147,147,'Palau');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (260.0,'','','',148,148,'Panama');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',149,149,'Papua New Guinea');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',150,150,'Paraguay');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',151,151,'Peru');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',152,152,'Philippines');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',153,153,'Poland');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',154,154,'Portugal');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',220.0,'','',155,155,'Puerto Rico');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',339.0,'','',156,156,'Qatar');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',157,157,'Romania');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',158,158,'Russian Federation');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',159,159,'Rwanda');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (840.0,40.0,356.1,133.0,160,160,'Samoa');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (198.0,'','','',161,161,'San Marino');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',10.0,195.5,46.0,162,162,'Sao Tome and Principe');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (114.0,'','','',163,163,'Saudi Arabia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',164,164,'Senegal');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',165,165,'Serbia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',23.0,910.3,24.0,166,166,'Seychelles');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (495.0,'','','',167,167,'Sierra Leone');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',168,168,'Singapore');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',169,169,'Sint Maarten (Dutch part)');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (733.0,'','','',170,170,'Slovak Republic');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',171,171,'Slovenia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',172,172,'Solomon Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (202.0,'','','',173,173,'Somalia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (609.0,'','','',174,174,'South Africa');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',175,175,'South Sudan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',176,176,'Spain');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',177,177,'Sri Lanka');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',15.0,'',30.0,178,178,'St. Kitts and Nevis');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (231.0,35.0,598.8,44.0,179,179,'St. Lucia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (407.0,'','','',180,180,'St. Martin (French part)');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',18.0,319.2,40.0,181,181,'St. Vincent and the Grenadines');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (209.0,'','','',182,182,'Sudan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',273.0,'',709.0,183,183,'Suriname');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',569.0,'','',184,184,'Eswatini');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',185,185,'Sweden');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',186,186,'Switzerland');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',187,187,'Syrian Arab Republic');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',188,188,'Tajikistan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',189,189,'Tanzania');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',190,190,'Thailand');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (469.0,226.0,959.3,732.0,191,191,'Timor-Leste');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',192,192,'Togo');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (121.0,22.0,155.3,61.0,193,193,'Tonga');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',281.0,'','',194,194,'Trinidad and Tobago');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',195,195,'Tunisia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',196,196,'Turkey');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',197,197,'Turkmenistan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (205.0,1.0,'',6.0,198,198,'Turks and Caicos Islands');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (11.0,1.0,5.2,3.0,199,199,'Tuvalu');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',200,200,'Uganda');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',201,201,'Ukraine');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',202,202,'United Arab Emirates');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',203,203,'United Kingdom');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',204,204,'United States');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',205,205,'Uruguay');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',206,206,'Uzbekistan');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES (154.0,109.0,446.2,254.0,207,207,'Vanuatu');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',208,208,'Venezuela, RB');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',209,209,'Vietnam');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('',13.0,61.5,47.0,210,210,'Virgin Islands (U.S.)');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',211,211,'West Bank and Gaza');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',212,212,'Yemen, Rep.');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',213,213,'Zambia');
INSERT INTO Environment.EmissionData(CarbonDioxideEmissions,NitrousOxideEmissions,TotalGHGEmissions,MethaneEmissions,EmissionID,CountryID,Name) VALUES ('','','','',214,214,'Zimbabwe');
